'use strict';

/**
 * Authentication & Authorization Middleware.
 *
 * Supports two authentication methods (either is sufficient):
 *
 *  1. JWT Bearer token  – `Authorization: Bearer <token>`
 *     Issued by POST /api/auth/token.  Contains `sub`, `scopes`, `iat`, `exp`.
 *     Key rotation supported via config.jwt.previousSecrets.
 *
 *  2. API Key           – `X-Api-Key: lba_v1_<hex>`
 *     Generated by POST /api/admin/api-keys (admin only).
 *     HMAC of the raw key is stored; the raw key is never persisted.
 *
 * Scope checking: pass `requireScope('vote:write')` after `authenticate`.
 */

const jwt = require('jsonwebtoken');
const config = require('../config/security');
const { hashApiKey } = require('../services/crypto');
const db = require('../database/db');
const auditLog = require('../services/auditLog');

// ── JWT helpers ───────────────────────────────────────────────────────────────

/**
 * Try to verify a token against the current secret and all previous secrets.
 */
function verifyJwt(token) {
  const secrets = [config.jwt.secret, ...config.jwt.previousSecrets].filter(Boolean);
  let lastErr;
  for (const secret of secrets) {
    try {
      return jwt.verify(token, secret);
    } catch (err) {
      lastErr = err;
    }
  }
  throw lastErr;
}

// ── Core authenticate middleware ──────────────────────────────────────────────

/**
 * Authenticate the request using JWT or API Key.
 * On success, attaches `req.auth` with `{ sub, scopes, method, apiKeyId? }`.
 * On failure, returns 401.
 */
function authenticate(req, res, next) {
  const authHeader = req.headers['authorization'];
  const apiKeyHeader = req.headers['x-api-key'];

  // ── Try JWT ───────────────────────────────────────────────────────────────
  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.slice(7);
    try {
      const payload = verifyJwt(token);
      req.auth = {
        sub: payload.sub,
        scopes: Array.isArray(payload.scopes) ? payload.scopes : [],
        method: 'jwt',
      };
      return next();
    } catch (err) {
      auditLog.append({
        action: 'AUTH_FAILURE_JWT',
        actor: 'unknown',
        data: { reason: err.message, ip: req.ip },
      });
      return res.status(401).json({ error: 'Invalid or expired JWT token' });
    }
  }

  // ── Try API Key ───────────────────────────────────────────────────────────
  if (apiKeyHeader) {
    const keyHash = hashApiKey(apiKeyHeader);
    const keyRecord = db.getApiKeyByHash(keyHash);
    if (!keyRecord) {
      auditLog.append({
        action: 'AUTH_FAILURE_API_KEY',
        actor: 'unknown',
        data: { ip: req.ip },
      });
      return res.status(401).json({ error: 'Invalid or revoked API key' });
    }

    db.touchApiKey(keyRecord.id);
    req.auth = {
      sub: keyRecord.id,
      scopes: (keyRecord.scopes || '').split(',').map(s => s.trim()).filter(Boolean),
      method: 'api_key',
      apiKeyId: keyRecord.id,
    };
    return next();
  }

  return res.status(401).json({ error: 'Authentication required (Bearer token or X-Api-Key)' });
}

// ── Scope guard ───────────────────────────────────────────────────────────────

/**
 * Middleware factory – requires that `req.auth.scopes` includes `scope`.
 */
function requireScope(scope) {
  return (req, res, next) => {
    if (!req.auth || !req.auth.scopes.includes(scope)) {
      auditLog.append({
        action: 'AUTHZ_FAILURE',
        actor: req.auth ? req.auth.sub : 'unknown',
        data: { requiredScope: scope, providedScopes: req.auth ? req.auth.scopes : [], ip: req.ip },
      });
      return res.status(403).json({ error: `Insufficient permissions. Required scope: ${scope}` });
    }
    next();
  };
}

// ── Admin JWT issuance ────────────────────────────────────────────────────────

/**
 * Issue a short-lived JWT for the given subject and scopes.
 * Used by POST /api/auth/token.
 */
function issueJwt(sub, scopes) {
  return jwt.sign({ sub, scopes }, config.jwt.secret, {
    expiresIn: config.jwt.expiry,
    issuer: 'like-button-api',
  });
}

/**
 * Issue a long-lived admin JWT (uses a separate secret).
 */
function issueAdminJwt(sub) {
  return jwt.sign(
    { sub, scopes: ['vote:read', 'vote:write', 'admin', 'audit:read', 'forensics'] },
    config.adminJwt.secret,
    { expiresIn: config.adminJwt.expiry, issuer: 'like-button-api' },
  );
}

module.exports = {
  authenticate,
  requireScope,
  issueJwt,
  issueAdminJwt,
};
